export const theme = {
  fontSize: {
    xxxxs: '0.5rem',
    xxxs: '0.8rem',
    xxs: '1rem',
    xs: '1.2rem',
    s: '1.6rem',
    m: '2.1rem',
    l: '2.4rem',
    xl: '3rem',
    xxl: '3.2rem',
    xxxl: '4rem',
    xxxxl: '4.8rem',
    xxxxxl: '5.4rem',
    xxxxxxl: '6rem',
  },
  fontWeights: {
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
  },
  colors: {
    general: {
      green: '#00CC96',
      white: '#FFFFFF',
      greenShadow: 'rgba(0, 204, 150, 0.2)',
      checkboxBorder: '#F4F4F4',
      socialMediaButtonBackground: '#FFFFFF',
      socialMediaButtonText: '#041C3F',
      socialMediaButtonShadow: 'rgba(174, 174, 192, 0.2)',
      requiredStar: '#FF3535',
    },
    home: {
      background: '#FAFAFA',
      formText: '#041C3F',
      formInput: '#7F8B9C',
      formInputShadow: 'rgba(174, 174, 192, 0.2)',
      formInputBorder: '#F4F4F4',
      greenLabel: '#00CC96',
      markdownLine: '#F4F4F4',
      whiteLabel: '#FFFFFF',
      ORLabelText: '#7F8B9C',
    },
    dashboard: {
      sidebarBackground: '#FFFFFF',
      sidebarActiveBackground: '#F2FCFA',
      sidebarActiveText: '#00CC96',
      sidebarText: '#7F8B9C',
      sidebarIcon: '#7F8B9C',
      dashboardBackground: '#F2F2F2',
      dashboardElementBackground: '#FFFFFF',
      dashboardTextLight: '#7F8B9C',
      dashboardTextDark: '#041C3F',
      dashboardTextGreen: '#00CC96',
      dashboardElementBorder: '#F4F4F4',
      greenLabel: '#00CC96',
      shadow: 'rgba(174, 174, 192, 0.1)',
      calendarActiveBackground: '#F2FCFA',
      textLine: '#D3E2DE',
    },
  },
};
